apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  namespace: mani
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    app: mani
  template:
    metadata:
      name: manipod
      labels:
        app:mani
    spec:
      containers:
      - name: manicont
        image: manisl339/manimw:${buildnum}
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: maniser
spec:
  type: ClusterIP
  selecter:
    app: mani
  ports:
  - port: 80
    targetPort: 8080 
  
        
